packages:
    - apps/front
    - apps/ui
    - apps/shared
    - apps/shared-api
    - apps/api-gateway
    - apps/api-user
    - apps/api-mail
    - apps/api-book
    - apps/api-conversation
    - apps/healthcheck
